import { AlertContextComponent } from '@/contexts/alertContext'
import { UserContextComponent } from '@/contexts/userContext'
import '@/styles/global.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <UserContextComponent>
          <AlertContextComponent>
            <main className="managementContainer">{children}</main>
          </AlertContextComponent>
        </UserContextComponent>
      </body>
    </html>
  )
}
