version: "3.7"
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    expose:
      - 5432
    network_mode: host
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  app:
    depends_on: [postgres-db]
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: rentx-webservice
    network_mode: host
    volumes:
      - .:/usr/app