name: 'Runing tests and deploy'
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: 'Running tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout files'
        uses: 'actions/checkout@v4'

      - name: 'Node version'
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - run: cd back
      - run: npm ci
      - run: npm run test

  build-image:
    needs: tests
    name: 'Build Docker image'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout files'
        uses: actions/checkout@v4

      - name: 'Login Docker Hub'
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: 'Build docker image'
        run: docker build -t johnatanso/rentx-webservice -f /back/Dockerfile.production .
      
      - name: 'Push image to Docker Hu'
        run: docker push johnatanso/rentx-webservice:latest

