import { AlertContextComponent } from '@/contexts/alertContext'
import '@/styles/global.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AlertContextComponent>
          <main className="authContainerPage">{children}</main>
        </AlertContextComponent>
      </body>
    </html>
  )
}
