name: 'Runing tests and deploy'
on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
jobs:
  tests:
    name: 'Running tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout files'
        uses: 'actions/checkout@v4'

      - name: 'Node version'
        uses: actions/setup-node@v4
        with: 
          node-version: 'node'

      - run: npm ci
        working-directory: back

      - run: npm run test
        working-directory: back

  build-image:
    needs: tests
    name: 'Build Docker image'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout files'
        uses: actions/checkout@v4

      - name: 'Login Docker Hub'
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        working-directory: back

      - name: 'Build docker image'
        run: docker build -t johnatanso/rentx-webservice:latest -f Dockerfile.production .
        working-directory: back
      
      - name: 'Push image to Docker Hu'
        run: docker push johnatanso/rentx-webservice:latest
        working-directory: back

  deploy-app:
    needs: build-image
    name: 'Deploy aplication'
    runs-on: self-hosted

    steps:
      - name: 'Login Docker Hub'
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: 'Removing old container'
        run:  docker rm -f rentx-webservice
      
      - name: 'Pull image from Docker Hub'
        run: docker pull johnatanso/rentx-webservice:latest
      
      - name: 'Run imagem'
        run: docker run -d -p 3333:3333 --name rentx-webservice --restart always johnatanso/rentx-webservice:latest
